import type {
  JobSeeker, Mentor, Trainer, Course, ConsultationRequest,
  AssessmentQuestion, RoadmapItem, AdminStats, User
} from './types';

export const demoJobSeekers: JobSeeker[] = [
  {
    id: 'js-1',
    name: 'Sara Ahmadi',
    email: 'sara.ahmadi@email.com',
    role: 'job-seeker',
    avatar: 'https://ui-avatars.com/api/?name=Sara+Ahmadi&background=6175f5&color=fff',
    phone: '+98 912 345 6789',
    location: 'Tehran, Iran',
    bio: 'Marketing professional with 4 years of experience in digital marketing and brand management.',
    headline: 'Digital Marketing Specialist | Brand Strategist',
    employabilityScore: 72,
    profileCompletion: 78,
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Social Media', 'Google Analytics', 'Brand Management'],
    languages: [
      { name: 'Persian', level: 'Native' },
      { name: 'English', level: 'Fluent' },
      { name: 'French', level: 'Beginner' },
    ],
    experience: [
      {
        id: 'exp-1',
        company: 'Digikala',
        title: 'Senior Marketing Specialist',
        startDate: '2022-03',
        current: true,
        description: 'Leading digital marketing campaigns and managing brand presence across channels.',
      },
      {
        id: 'exp-2',
        company: 'Snapp Group',
        title: 'Marketing Coordinator',
        startDate: '2020-06',
        endDate: '2022-02',
        current: false,
        description: 'Coordinated marketing activities and supported campaign execution.',
      },
    ],
    education: [
      {
        id: 'edu-1',
        institution: 'University of Tehran',
        degree: 'Bachelor of Science',
        field: 'Business Administration',
        startDate: '2016-09',
        endDate: '2020-06',
        current: false,
      },
    ],
    assessmentCompleted: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'js-2',
    name: 'Ali Rezaei',
    email: 'ali.rezaei@email.com',
    role: 'job-seeker',
    avatar: 'https://ui-avatars.com/api/?name=Ali+Rezaei&background=14b8a6&color=fff',
    phone: '+98 921 987 6543',
    location: 'Isfahan, Iran',
    bio: 'Software engineer passionate about building scalable web applications.',
    headline: 'Full-Stack Developer | React & Node.js',
    employabilityScore: 85,
    profileCompletion: 92,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Docker', 'AWS'],
    languages: [
      { name: 'Persian', level: 'Native' },
      { name: 'English', level: 'Professional' },
    ],
    experience: [
      {
        id: 'exp-3',
        company: 'Cafe Bazaar',
        title: 'Frontend Developer',
        startDate: '2021-01',
        current: true,
        description: 'Building and maintaining React-based web applications for millions of users.',
      },
    ],
    education: [
      {
        id: 'edu-2',
        institution: 'Sharif University of Technology',
        degree: 'Bachelor of Science',
        field: 'Computer Engineering',
        startDate: '2017-09',
        endDate: '2021-06',
        current: false,
      },
    ],
    assessmentCompleted: false,
    createdAt: '2024-02-20',
  },
];

export const demoMentors: Mentor[] = [
  {
    id: 'mentor-1',
    name: 'Dr. Leila Hosseini',
    email: 'leila.hosseini@email.com',
    role: 'mentor',
    avatar: 'https://ui-avatars.com/api/?name=Leila+Hosseini&background=f97316&color=fff',
    phone: '+98 911 222 3333',
    location: 'Tehran, Iran',
    bio: 'Former HR Director with 15+ years of experience in talent development and career coaching.',
    expertise: ['Career Coaching', 'HR Management', 'Leadership Development', 'Executive Presence'],
    hourlyRate: 150,
    rating: 4.9,
    totalSessions: 248,
    availability: ['Monday', 'Wednesday', 'Friday'],
    approvalStatus: 'approved',
    createdAt: '2023-11-10',
  },
  {
    id: 'mentor-2',
    name: 'Reza Karimi',
    email: 'reza.karimi@email.com',
    role: 'mentor',
    avatar: 'https://ui-avatars.com/api/?name=Reza+Karimi&background=6175f5&color=fff',
    phone: '+98 935 444 5555',
    location: 'Mashhad, Iran',
    bio: 'Entrepreneur and startup advisor with experience in tech and e-commerce sectors.',
    expertise: ['Entrepreneurship', 'Product Management', 'Growth Strategy', 'Tech Startups'],
    hourlyRate: 120,
    rating: 4.7,
    totalSessions: 183,
    availability: ['Tuesday', 'Thursday', 'Saturday'],
    approvalStatus: 'approved',
    createdAt: '2023-12-05',
  },
  {
    id: 'mentor-3',
    name: 'Mina Sadeghi',
    email: 'mina.sadeghi@email.com',
    role: 'mentor',
    avatar: 'https://ui-avatars.com/api/?name=Mina+Sadeghi&background=ec4899&color=fff',
    phone: '+98 912 666 7777',
    location: 'Shiraz, Iran',
    bio: 'Data scientist and AI researcher helping professionals transition into tech careers.',
    expertise: ['Data Science', 'Machine Learning', 'Python', 'Career Transition to Tech'],
    hourlyRate: 130,
    rating: 4.8,
    totalSessions: 127,
    availability: ['Monday', 'Tuesday', 'Thursday'],
    approvalStatus: 'pending',
    createdAt: '2024-01-20',
  },
];

export const demoTrainers: Trainer[] = [
  {
    id: 'trainer-1',
    name: 'Kamran Nasiri',
    email: 'kamran.nasiri@email.com',
    role: 'trainer',
    avatar: 'https://ui-avatars.com/api/?name=Kamran+Nasiri&background=8b5cf6&color=fff',
    phone: '+98 919 888 9999',
    location: 'Tehran, Iran',
    bio: 'Digital marketing expert with 10+ years of teaching experience.',
    specialization: ['Digital Marketing', 'SEO', 'Content Marketing'],
    totalCourses: 8,
    totalStudents: 1240,
    approvalStatus: 'approved',
    createdAt: '2023-10-15',
  },
  {
    id: 'trainer-2',
    name: 'Zahra Mohammadi',
    email: 'zahra.mohammadi@email.com',
    role: 'trainer',
    avatar: 'https://ui-avatars.com/api/?name=Zahra+Mohammadi&background=0ea5e9&color=fff',
    phone: '+98 901 111 2222',
    location: 'Tehran, Iran',
    bio: 'Software development trainer specializing in modern web technologies.',
    specialization: ['Web Development', 'React', 'Node.js', 'TypeScript'],
    totalCourses: 5,
    totalStudents: 890,
    approvalStatus: 'approved',
    createdAt: '2023-11-01',
  },
];

export const demoCourses: Course[] = [
  {
    id: 'course-1',
    trainerId: 'trainer-1',
    trainerName: 'Kamran Nasiri',
    title: 'Complete Digital Marketing Masterclass',
    titleFa: 'دوره جامع بازاریابی دیجیتال',
    description: 'Master digital marketing from SEO to social media, email campaigns, and analytics.',
    descriptionFa: 'از سئو تا رسانه‌های اجتماعی، کمپین‌های ایمیل و آنالیتیکس را تسلط پیدا کنید.',
    category: 'Marketing',
    duration: '32 hours',
    level: 'intermediate',
    price: 2500000,
    status: 'published',
    enrollments: 342,
    rating: 4.8,
    thumbnail: 'https://picsum.photos/seed/marketing/400/250',
    createdAt: '2024-01-10',
    approvalStatus: 'approved',
  },
  {
    id: 'course-2',
    trainerId: 'trainer-2',
    trainerName: 'Zahra Mohammadi',
    title: 'React & TypeScript — Build Modern Web Apps',
    titleFa: 'ری‌اکت و تایپ‌اسکریپت — ساخت اپلیکیشن‌های وب مدرن',
    description: 'Learn to build production-ready React applications with TypeScript and best practices.',
    descriptionFa: 'یاد بگیرید چطور اپلیکیشن‌های ری‌اکت آماده برای محصول با تایپ‌اسکریپت و بهترین روش‌ها بسازید.',
    category: 'Technology',
    duration: '45 hours',
    level: 'intermediate',
    price: 3200000,
    status: 'published',
    enrollments: 218,
    rating: 4.9,
    thumbnail: 'https://picsum.photos/seed/react/400/250',
    createdAt: '2024-01-25',
    approvalStatus: 'approved',
  },
  {
    id: 'course-3',
    trainerId: 'trainer-1',
    trainerName: 'Kamran Nasiri',
    title: 'LinkedIn Profile Optimization for Job Seekers',
    titleFa: 'بهینه‌سازی پروفایل لینکدین برای کارجویان',
    description: 'Build a compelling LinkedIn profile that attracts recruiters and opportunities.',
    descriptionFa: 'یک پروفایل لینکدین جذاب بسازید که کارفرمایان و فرصت‌ها را جذب کند.',
    category: 'Career Development',
    duration: '6 hours',
    level: 'beginner',
    price: 850000,
    status: 'published',
    enrollments: 567,
    rating: 4.7,
    thumbnail: 'https://picsum.photos/seed/linkedin/400/250',
    createdAt: '2024-02-05',
    approvalStatus: 'approved',
  },
  {
    id: 'course-4',
    trainerId: 'trainer-2',
    trainerName: 'Zahra Mohammadi',
    title: 'Python for Data Analysis',
    titleFa: 'پایتون برای تحلیل داده',
    description: 'Learn data manipulation, visualization, and analysis with Python and pandas.',
    descriptionFa: 'دستکاری داده، بصری‌سازی و تحلیل با پایتون و پانداس را یاد بگیرید.',
    category: 'Data Science',
    duration: '28 hours',
    level: 'beginner',
    price: 2100000,
    status: 'draft',
    enrollments: 0,
    rating: undefined,
    thumbnail: 'https://picsum.photos/seed/python/400/250',
    createdAt: '2024-03-10',
    approvalStatus: 'pending',
  },
];

export const demoRequests: ConsultationRequest[] = [
  {
    id: 'req-1',
    jobSeekerId: 'js-1',
    jobSeekerName: 'Sara Ahmadi',
    mentorId: 'mentor-1',
    mentorName: 'Dr. Leila Hosseini',
    subject: 'Career transition to product management',
    message: 'I have 4 years in marketing and want to transition to product management. Looking for guidance on skills to develop and how to position my experience.',
    status: 'pending',
    createdAt: '2024-03-15',
  },
  {
    id: 'req-2',
    jobSeekerId: 'js-2',
    jobSeekerName: 'Ali Rezaei',
    mentorId: 'mentor-2',
    mentorName: 'Reza Karimi',
    subject: 'Building a startup while employed',
    message: 'I am a developer with a startup idea. Need advice on how to validate the idea and take the first steps while still employed.',
    status: 'accepted',
    createdAt: '2024-03-10',
    sessionDate: '2024-03-25',
    notes: 'Discussed lean startup methodology and MVP planning. Next session to focus on technical architecture.',
  },
  {
    id: 'req-3',
    jobSeekerId: 'js-1',
    jobSeekerName: 'Sara Ahmadi',
    mentorId: 'mentor-2',
    mentorName: 'Reza Karimi',
    subject: 'Improving my personal brand',
    message: 'Looking for advice on building a stronger professional brand on LinkedIn and in my industry.',
    status: 'completed',
    createdAt: '2024-02-20',
    sessionDate: '2024-03-01',
    notes: 'Great session. Sara has a strong foundation. Recommended starting a content series on marketing trends.',
  },
];

export const assessmentQuestions: AssessmentQuestion[] = [
  {
    id: 'q-1',
    category: 'Skills & Competencies',
    question: 'How would you rate your core professional skills relevant to your target role?',
    questionFa: 'مهارت‌های اصلی حرفه‌ای خود را در رابطه با نقش هدفتان چطور ارزیابی می‌کنید؟',
    options: [
      { value: '1', label: 'Beginner — Still developing foundational skills', labelFa: 'مبتدی — هنوز در حال توسعه مهارت‌های پایه' },
      { value: '2', label: 'Developing — Have some skills but need more practice', labelFa: 'در حال توسعه — چند مهارت دارم اما به تمرین بیشتر نیاز دارم' },
      { value: '3', label: 'Proficient — Can handle most tasks independently', labelFa: 'ماهر — می‌توانم اکثر وظایف را به طور مستقل انجام دهم' },
      { value: '4', label: 'Expert — Highly skilled, can lead and mentor others', labelFa: 'متخصص — بسیار ماهر، می‌توانم رهبری کنم و به دیگران مشاوره دهم' },
    ],
  },
  {
    id: 'q-2',
    category: 'Work Experience',
    question: 'How much relevant work experience do you have in your target field?',
    questionFa: 'چه مقدار تجربه کاری مرتبط در حوزه هدفتان دارید؟',
    options: [
      { value: '1', label: 'None — This is a new area for me', labelFa: 'هیچ — این حوزه برای من جدید است' },
      { value: '2', label: '1–2 years — Entry-level experience', labelFa: '۱–۲ سال — تجربه سطح ابتدایی' },
      { value: '3', label: '3–5 years — Mid-level experience', labelFa: '۳–۵ سال — تجربه سطح متوسط' },
      { value: '4', label: '5+ years — Senior-level experience', labelFa: '۵+ سال — تجربه سطح ارشد' },
    ],
  },
  {
    id: 'q-3',
    category: 'Professional Network',
    question: 'How strong is your professional network in your target industry?',
    questionFa: 'شبکه حرفه‌ای شما در صنعت هدف چقدر قوی است؟',
    options: [
      { value: '1', label: 'Minimal — I have few industry connections', labelFa: 'حداقل — ارتباطات صنعتی کمی دارم' },
      { value: '2', label: 'Growing — Building connections actively', labelFa: 'در حال رشد — فعالانه در حال ایجاد ارتباط هستم' },
      { value: '3', label: 'Established — Good network within the field', labelFa: 'تثبیت شده — شبکه خوبی در این حوزه دارم' },
      { value: '4', label: 'Strong — Influential connections and industry visibility', labelFa: 'قوی — ارتباطات تأثیرگذار و دیده شدن در صنعت' },
    ],
  },
  {
    id: 'q-4',
    category: 'CV & Personal Brand',
    question: 'How would you describe the quality of your current CV and online presence?',
    questionFa: 'کیفیت رزومه فعلی و حضور آنلاین خود را چطور توصیف می‌کنید؟',
    options: [
      { value: '1', label: 'Poor — Outdated or no CV, no online presence', labelFa: 'ضعیف — رزومه قدیمی یا بدون رزومه، بدون حضور آنلاین' },
      { value: '2', label: 'Basic — Simple CV, minimal online presence', labelFa: 'پایه — رزومه ساده، حضور آنلاین حداقل' },
      { value: '3', label: 'Good — Professional CV, active LinkedIn profile', labelFa: 'خوب — رزومه حرفه‌ای، پروفایل لینکدین فعال' },
      { value: '4', label: 'Excellent — Strong brand, portfolio, thought leadership', labelFa: 'عالی — برند قوی، پورتفولیو، رهبری فکری' },
    ],
  },
  {
    id: 'q-5',
    category: 'Interview Readiness',
    question: 'How confident are you in your interview and job application skills?',
    questionFa: 'چقدر در مهارت‌های مصاحبه و درخواست شغلی خود اعتماد به نفس دارید؟',
    options: [
      { value: '1', label: 'Not confident — Struggling with interviews', labelFa: 'بدون اعتماد به نفس — در مصاحبه مشکل دارم' },
      { value: '2', label: 'Slightly confident — Some experience but room for improvement', labelFa: 'کمی اعتماد به نفس — کمی تجربه دارم اما جای بهبود وجود دارد' },
      { value: '3', label: 'Fairly confident — Comfortable with standard interviews', labelFa: 'نسبتاً با اعتماد — با مصاحبه‌های معمول راحت هستم' },
      { value: '4', label: 'Very confident — Excel at interviews, strong track record', labelFa: 'بسیار با اعتماد — در مصاحبه عالی هستم، سابقه موفق دارم' },
    ],
  },
];

export const demoRoadmap: RoadmapItem[] = [
  {
    id: 'road-1',
    title: 'Complete Your Professional Profile',
    titleFa: 'پروفایل حرفه‌ای خود را تکمیل کنید',
    description: 'Fill in all sections of your Movian profile including experience, education, skills, and bio.',
    descriptionFa: 'تمام بخش‌های پروفایل موویان خود را شامل تجربه، تحصیلات، مهارت‌ها و بیوگرافی پر کنید.',
    category: 'skill',
    priority: 'high',
    estimatedTime: '2 hours',
    completed: true,
  },
  {
    id: 'road-2',
    title: 'Optimize Your LinkedIn Profile',
    titleFa: 'پروفایل لینکدین خود را بهینه کنید',
    description: 'Update your LinkedIn with a professional photo, compelling headline, and detailed experience.',
    descriptionFa: 'لینکدین خود را با عکس حرفه‌ای، عنوان جذاب و تجربه دقیق به‌روز کنید.',
    category: 'skill',
    priority: 'high',
    estimatedTime: '3 hours',
    completed: false,
    resources: ['LinkedIn Profile Optimization Course', 'Personal Branding Guide'],
  },
  {
    id: 'road-3',
    title: 'Complete Digital Marketing Course',
    titleFa: 'دوره بازاریابی دیجیتال را تکمیل کنید',
    description: 'Enroll in and complete the Digital Marketing Masterclass to strengthen your core skills.',
    descriptionFa: 'در دوره جامع بازاریابی دیجیتال ثبت‌نام کنید و آن را تکمیل کنید تا مهارت‌های اصلی خود را تقویت کنید.',
    category: 'course',
    priority: 'high',
    estimatedTime: '32 hours',
    completed: false,
    resources: ['Complete Digital Marketing Masterclass'],
  },
  {
    id: 'road-4',
    title: 'Schedule a Career Strategy Session',
    titleFa: 'یک جلسه استراتژی شغلی برنامه‌ریزی کنید',
    description: 'Book a consultation with a career mentor to discuss your transition strategy.',
    descriptionFa: 'یک مشاوره با منتور شغلی رزرو کنید تا استراتژی انتقال شغلی خود را بررسی کنید.',
    category: 'experience',
    priority: 'medium',
    estimatedTime: '1 hour',
    completed: false,
  },
  {
    id: 'road-5',
    title: 'Build a Portfolio of Marketing Projects',
    titleFa: 'یک پورتفولیو از پروژه‌های بازاریابی بسازید',
    description: 'Create 3-5 case studies showcasing your marketing campaigns and their results.',
    descriptionFa: '۳–۵ مطالعه موردی ایجاد کنید که کمپین‌های بازاریابی و نتایج آنها را نشان دهد.',
    category: 'experience',
    priority: 'medium',
    estimatedTime: '2 weeks',
    completed: false,
  },
  {
    id: 'road-6',
    title: 'Obtain Google Analytics Certification',
    titleFa: 'گواهینامه گوگل آنالیتیکس دریافت کنید',
    description: 'Complete the Google Analytics Individual Qualification to boost your data credibility.',
    descriptionFa: 'مدرک انفرادی گوگل آنالیتیکس را تکمیل کنید تا اعتبار داده‌ای خود را تقویت کنید.',
    category: 'certification',
    priority: 'medium',
    estimatedTime: '10 hours',
    completed: false,
  },
  {
    id: 'road-7',
    title: 'Apply to 5 Target Roles Per Week',
    titleFa: 'هفته‌ای ۵ نقش هدف درخواست دهید',
    description: 'Systematically apply to relevant positions and track your applications in the dashboard.',
    descriptionFa: 'به طور منظم برای موقعیت‌های مرتبط درخواست دهید و درخواست‌هایتان را در داشبورد دنبال کنید.',
    category: 'experience',
    priority: 'low',
    estimatedTime: 'Ongoing',
    completed: false,
  },
];

export const adminStats: AdminStats = {
  totalUsers: 1847,
  jobSeekers: 1523,
  mentors: 187,
  trainers: 62,
  pendingMentors: 14,
  pendingTrainers: 8,
  pendingCourses: 11,
  totalCourses: 94,
  totalRequests: 3241,
  pendingRequests: 234,
  monthlyGrowth: 18.4,
};

export const demoAdminUsers: User[] = [
  ...demoJobSeekers,
  ...demoMentors,
  ...demoTrainers,
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@movian.io',
    role: 'admin',
    createdAt: '2023-01-01',
  },
];
